### ISSUE TITLE
Files are not being read/opened

### ISSUE THREAD

**Issue by musa11971** [szymonkaliski/parametrium#1]
My sketch does not seem to be loading into Parametrium

demo: https://gyazo.com/9ab2b9a90f6a4e52dac8facddae3039c

**Comment by szymonkaliski** [comment]
Thanks for letting me know! Can you tell me what browser are you using, and can you send the sketch file you are using, so I can test?

**Comment by musa11971** [comment]
Chrome v56.0.2924.87 (64-bit)

[sketch file](https://pastebin.com/5AWvqsXA)

also, I just now noticed the javascript [error](http://i.imgur.com/WXnAvDi.png)

**Comment by szymonkaliski** [comment]
Thanks! looks like there's a problem with file uploads on windows, I'll investigate this and get back to you.

**Comment by szymonkaliski** [comment]
fixed in https://github.com/szymonkaliski/parametrium/commit/169ead475e85c61a36b3ce736477d08b88e9c203 -- should work now! :)
